sonar.projectKey=creiddom_php-project-9
sonar.organization=creiddom

sonar.sources=public,src,templates,config
sonar.tests=tests
sonar.exclusions=vendor/**,**/vendor/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/templates/**,**/public/**,**/config/**
